#!/bin/bash

# Function to display subdomain information
display_info() {
  record_type=$(dig +short -t $2 $1 | awk '{print toupper($1)}')
  if [ -z "$record_type" ]; then
    echo "The subdomain $1 does not exist"
  else
    destination=$(dig +short $1 | awk '{print $1}')
    echo "The subdomain $1 is a $record_type record and points to $destination"
  fi
}

# Check if domain argument is provided
if [ -z "$1" ]; then
  echo "Please provide a domain name"
  exit 1
fi

# Display information for specific subdomain if subdomain argument is provided
if [ ! -z "$2" ]; then
  display_info "$2.$1" A
else
  # Display information for default subdomains
  display_info "www.$1" CNAME
  display_info "lb-01.$1" A
  display_info "web-01.$1" A
  display_info "web-02.$1" A
fi
